### PR TITLE
updated the top section of about us page + readme adoc file + setup coveralls and appveyor + added shorthand command for clear and find (with updated tests and userguide)

### PR DESCRIPTION
**Pull request by windrichie**

### CODE REVIEW

**Review by Sameow — APPROVED** [review]
nice

**Review by Shizhe-NUS — APPROVED** [review]
nice job bro

**Review by Sameow — CHANGES_REQUESTED** [review]
Resolve the conflicts pls

**Comment by windrichie** [comment]
conflicts resolved!

**Review by Sameow — APPROVED** [review]

**Pull request merged**
