### PR TITLE
added profile photo windrichie.jpg, changed to png and changed Ui.png

### PR DESCRIPTION
**Pull request by windrichie**
added photo

### CODE REVIEW

**Comment by windrichie** [comment]
Updated the about us page to include my picture + added windrich.adoc portfolio page under doc/team/

**Review by Sameow — APPROVED** [review]
oh yea change pls

**Review by JKupoluyi — COMMENTED** [review]
Your picture will not show with the jpg extension, you have to use ".png".

**Review by Sameow — CHANGES_REQUESTED** [review]
oh yea change to png

**Review by Sameow — APPROVED** [review]

**Pull request merged**
