### PR TITLE
developer guide updated

### PR DESCRIPTION
**Pull request by Shizhe-NUS**
This is the existing contents to be added in this developer guide.Further instruction is awaiting.

### CODE REVIEW

**Comment by windrichie** [comment]
Should we also include the table with user stories inside this developer guide?

**Comment by Sameow** [comment]
> Should we also include the table with user stories inside this developer guide?

Yea i think we should

**Review by Sameow — CHANGES_REQUESTED** [review]
Add user stories plox

**Comment by Shizhe-NUS** [comment]
> Should we also include the table with user stories inside this developer guide?

In others' developer guide they didn't seem to put in a table like user cases.

**Review by Sameow — APPROVED** [review]

**Review by JKupoluyi — APPROVED** [review]
Seems good to me.

**Pull request merged**
